export interface Absence {
  Id: string;
  UserId: string;
  GroupId: string | null;
  FirstName: string | null;
  MiddleName: string | null;
  LastName: string | null;
  Timestamp: string | null;
  AbsenceDefinitionId: string | null;
  AbsenceDefinitionName: string;
  InsertedOn: string | null;
  ModifiedOn: string | null;
  Origin: number | null;
  OriginDisplayName: string | null;
  Comment: string | null;
  IsAuthentic: boolean | null;
  IconId: string | null;
  IconColor: string | null;
  IsCalculated: boolean | null;
  Status: number | null;
  ApprovalRequest: any | null;
  PartialTimeFrom: string;
  PartialTimeTo: string;
  PartialTimeDuration: number | null;
  IsPartial: boolean | null;
  OverrideHolidayAbsence: boolean | null;
  IsModified: boolean | null;
  ModifiedByUser: any | null;
  AbsenceDefinitionType: number | null;
}
